/**
 * VegePower - Google Keep Exporter Service
 * Formats ingredient lists into Google Keep checklist format
 * and provides Web Share API, keep.new deep-links, and 1-click clipboard sync.
 */

const KeepExporterService = {
  /**
   * Formats aggregated shopping items into a clean Google Keep checklist
   * @param {Object} shoppingList Categorized aisle items { "Produce": [...], "Protein & Chilled": [...] }
   * @param {Array} selectedRecipes List of selected recipe objects
   * @param {number} globalMultiplier Servings multiplier (1x, 2x, etc.)
   * @returns {string} Formatted text for Google Keep
   */
  formatKeepChecklist(shoppingList, selectedRecipes = [], globalMultiplier = 1) {
    const dateStr = new Date().toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric'
    });

    const recipeTitles = selectedRecipes.map(r => r.title).join(', ');
    let lines = [];

    // Note Header
    lines.push(`🌱 VEGETARIAN POWER SHOPPING LIST (${dateStr})`);
    if (recipeTitles) {
      lines.push(`Recipes (${globalMultiplier}x Servings): ${recipeTitles}`);
    }
    lines.push(`----------------------------------------`);
    lines.push(``);

    // Aisle Categories
    const categoryIcons = {
      "Produce": "🥦",
      "Protein & Chilled": "🫘",
      "Pantry": "🏺",
      "Spices": "🧂",
      "Other": "🛒"
    };

    let totalItems = 0;

    for (const [category, items] of Object.entries(shoppingList)) {
      if (items.length === 0) continue;

      const icon = categoryIcons[category] || "🛒";
      lines.push(`${icon} ${category.toUpperCase()}`);

      items.forEach(item => {
        const checkedMark = item.checked ? "[x]" : "[ ]";
        const formattedAmount = this.formatAmount(item.amount * globalMultiplier);
        const unitStr = item.unit ? ` ${item.unit}` : '';
        lines.push(`${checkedMark} ${formattedAmount}${unitStr} ${item.name}`);
        totalItems++;
      });

      lines.push(``);
    }

    lines.push(`----------------------------------------`);
    lines.push(`Total Items: ${totalItems} | Generated by VegePower`);

    return lines.join('\n');
  },

  /**
   * Native Web Share API Export (Optimal for Mobile Google Keep App integration)
   */
  async exportViaWebShare(title, text) {
    if (navigator.share) {
      try {
        await navigator.share({
          title: title || 'Vegetarian Shopping List - Google Keep',
          text: text
        });
        return { success: true, method: 'webshare' };
      } catch (err) {
        if (err.name !== 'AbortError') {
          console.warn('Web share failed, falling back:', err);
        } else {
          return { success: false, aborted: true };
        }
      }
    }

    // Fallback if Web Share API is not supported
    return this.openKeepNew(text);
  },

  /**
   * Deep link to Google Keep Web App (keep.new)
   */
  openKeepNew(text) {
    // Copy text first to clipboard so user can instantly paste into keep.new
    this.copyToClipboard(text);

    // Open keep.new in a new browser window/tab
    const keepUrl = `https://keep.new`;
    window.open(keepUrl, '_blank', 'noopener,noreferrer');

    return {
      success: true,
      method: 'keep.new',
      copied: true
    };
  },

  /**
   * Copies formatted Keep list to system clipboard
   */
  async copyToClipboard(text) {
    try {
      if (navigator.clipboard && navigator.clipboard.writeText) {
        await navigator.clipboard.writeText(text);
        return true;
      } else {
        // Fallback for older browsers
        const textarea = document.createElement('textarea');
        textarea.value = text;
        textarea.style.position = 'fixed';
        textarea.style.opacity = '0';
        document.body.appendChild(textarea);
        textarea.select();
        document.execCommand('copy');
        document.body.removeChild(textarea);
        return true;
      }
    } catch (err) {
      console.error('Clipboard copy error:', err);
      return false;
    }
  },

  /**
   * Helper to format numbers cleanly (e.g. 1.5 instead of 1.5000)
   */
  formatAmount(val) {
    if (!val || isNaN(val)) return '1';
    const rounded = Math.round(val * 100) / 100;
    return rounded.toString();
  }
};
